In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv('adult_with_headers (1).csv')
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [3]:
df.shape

(32561, 15)

In [4]:
df.size

488415

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [6]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(24)

In [12]:
df=df.drop_duplicates()

In [13]:
df.duplicated().sum()

np.int64(0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df['age']=sc.fit_transform(df[['age']])
df['fnlwgt']=sc.fit_transform(df[['fnlwgt']])
df['education_num']=sc.fit_transform(df[['education_num']])
df['capital_gain']=sc.fit_transform(df[['capital_gain']])
df['capital_loss']=sc.fit_transform(df[['capital_loss']])
df['hours_per_week']=sc.fit_transform(df[['hours_per_week']])

In [16]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.030390,State-gov,-1.063569,Bachelors,1.134777,Never-married,Adm-clerical,Not-in-family,White,Male,0.148292,-0.216743,-0.035664,United-States,<=50K
1,0.836973,Self-emp-not-inc,-1.008668,Bachelors,1.134777,Married-civ-spouse,Exec-managerial,Husband,White,Male,-0.145975,-0.216743,-2.222483,United-States,<=50K
2,-0.042936,Private,0.245040,HS-grad,-0.420679,Divorced,Handlers-cleaners,Not-in-family,White,Male,-0.145975,-0.216743,-0.035664,United-States,<=50K
3,1.056950,Private,0.425752,11th,-1.198407,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,-0.145975,-0.216743,-0.035664,United-States,<=50K
4,-0.776193,Private,1.408066,Bachelors,1.134777,Married-civ-spouse,Prof-specialty,Wife,Black,Female,-0.145975,-0.216743,-0.035664,Cuba,<=50K

In [19]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
for col in df.select_dtypes(include=['int','float']).columns:
    df[col]=ms.fit_transform(df[[col]])
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.301370,State-gov,0.044302,Bachelors,0.800000,Never-married,Adm-clerical,Not-in-family,White,Male,0.02174,0.0,0.397959,United-States,<=50K
1,0.452055,Self-emp-not-inc,0.048238,Bachelors,0.800000,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.00000,0.0,0.122449,United-States,<=50K
2,0.287671,Private,0.138113,HS-grad,0.533333,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.00000,0.0,0.397959,United-States,<=50K
3,0.493151,Private,0.151068,11th,0.400000,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.00000,0.0,0.397959,United-States,<=50K
4,0.150685,Private,0.221488,Bachelors,0.800000,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.00000,0.0,0.397959,Cuba,<=50K

1.Standard scaler:Converts features to mean 0 and standard deviation 1. Commonly used with Logistic Regression, SVM, KNN, PCA, and Neural Networks.
Preferred Scenario:
Data is approximately normally distributed or has varying ranges.
2.Minmaxscaler:Preserves the relative distribution of data and is useful for Neural Networks and distance-based algorithms.
Preffered scenario:
Data has a known bounded range and you want values between 0 and 1.

In [38]:
one_hot_cols = [col for col in df.select_dtypes(include=['object']) if df[col].nunique() < 5]
one_hot_cols

['sex', 'income']

In [48]:
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder,OneHotEncoder
oe=OneHotEncoder(sparse_output=False)
df['sex']=oe.fit_transform(df[['sex']])
df['income']=oe.fit_transform(df[['income']])

In [49]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.301370,State-gov,0.044302,Bachelors,0.800000,Never-married,Adm-clerical,Not-in-family,White,0.0,0.02174,0.0,0.397959,United-States,1.0
1,0.452055,Self-emp-not-inc,0.048238,Bachelors,0.800000,Married-civ-spouse,Exec-managerial,Husband,White,0.0,0.00000,0.0,0.122449,United-States,1.0
2,0.287671,Private,0.138113,HS-grad,0.533333,Divorced,Handlers-cleaners,Not-in-family,White,0.0,0.00000,0.0,0.397959,United-States,1.0
3,0.493151,Private,0.151068,11th,0.400000,Married-civ-spouse,Handlers-cleaners,Husband,Black,0.0,0.00000,0.0,0.397959,United-States,1.0
4,0.150685,Private,0.221488,Bachelors,0.800000,Married-civ-spouse,Prof-specialty,Wife,Black,1.0,0.00000,0.0,0.397959,Cuba,1.0

In [52]:
for i in df.select_dtypes(include=['object']).columns:
    print(i)

workclass
education
marital_status
occupation
relationship
race
native_country

In [54]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.select_dtypes(include=['object']).columns:
    df[i]=le.fit_transform(df[[i]])
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.301370,7,0.044302,9,0.800000,4,1,1,4,0.0,0.02174,0.0,0.397959,39,1.0
1,0.452055,6,0.048238,9,0.800000,2,4,0,4,0.0,0.00000,0.0,0.122449,39,1.0
2,0.287671,4,0.138113,11,0.533333,0,6,1,4,0.0,0.00000,0.0,0.397959,39,1.0
3,0.493151,4,0.151068,1,0.400000,2,6,0,2,0.0,0.00000,0.0,0.397959,39,1.0
4,0.150685,4,0.221488,9,0.800000,2,10,5,2,1.0,0.00000,0.0,0.397959,5,1.0

In [56]:
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.301370,7,0.044302,9,0.800000,4,1,1,4,0.0,0.021740,0.0,0.397959,39,1.0
1,0.452055,6,0.048238,9,0.800000,2,4,0,4,0.0,0.000000,0.0,0.122449,39,1.0
2,0.287671,4,0.138113,11,0.533333,0,6,1,4,0.0,0.000000,0.0,0.397959,39,1.0
3,0.493151,4,0.151068,1,0.400000,2,6,0,2,0.0,0.000000,0.0,0.397959,39,1.0
4,0.150685,4,0.221488,9,0.800000,2,10,5,2,1.0,0.000000,0.0,0.397959,5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,0.136986,4,0.166404,7,0.733333,2,13,5,4,1.0,0.000000,0.0,0.377551,39,1.0
32557,0.315068,4,0.096500,11,0.533333,2,7,0,4,0.0,0.000000,0.0,0.397959,39,0.0
32558,0.561644,4,0.094827,11,0.533333,6,1,4,4,1.0,0.000000,0.0,0.397959,39,1.0
32559,0.068493,4,0.128499,11,0.533333,4,1,3,4,0.0,0.000000,0.0,0.193878,39,1.0
32560,0.479452,5,0.187203,11,0.533333,2,4,5,4,1.0,0.150242,0.0,0.397959,39,0.0

In [57]:
df.shape

(32537, 15)

In [58]:
df.size

488055

In [59]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [60]:
df.duplicated().sum()

np.int64(0)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32537 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32537 non-null  float64
 1   workclass       32537 non-null  int64
 2   fnlwgt          32537 non-null  float64
 3   education       32537 non-null  int64
 4   education_num   32537 non-null  float64
 5   marital_status  32537 non-null  int64
 6   occupation      32537 non-null  int64
 7   relationship    32537 non-null  int64
 8   race            32537 non-null  int64
 9   sex             32537 non-null  float64
 10  capital_gain    32537 non-null  float64
 11  capital_loss    32537 non-null  float64
 12  hours_per_week  32537 non-null  float64
 13  native_country  32537 non-null  int64
 14  income          32537 non-null  float64
dtypes: float64(8), int64(7)
memory usage: 4.0 MB

In [62]:
df.describe()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
count,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000,32537.000000
mean,0.295692,3.868734,0.120547,10.297507,0.605454,2.611427,6.572856,1.446538,3.665827,0.330762,0.010785,0.020057,0.402452,36.721579,0.759074
std,0.186822,1.456445,0.071689,3.870142,0.171442,1.506301,4.229521,1.607064,0.848847,0.470495,0.073880,0.092539,0.125989,7.820732,0.427652
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.150685,4.000000,0.071679,9.000000,0.533333,2.000000,3.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.397959,39.000000,1.000000
50%,0.273973,4.000000,0.112788,11.000000,0.600000,2.000000,7.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.397959,39.000000,1.000000
75%,0.424658,4.000000,0.152611,12.000000,0.733333,4.000000,10.000000,3.000000,4.000000,1.000000,0.000000,0.000000,0.448980,39.000000,1.000000
max,1.000000,8.000000,1.000000,15.000000,1.000000,6.000000,14.000000,5.000000,4.000000,1.000000,1.000000,1.000000,1.000000,41.000000,1.000000

One-Hot Encoding:
pros:
• Does not create an artificial order between categories.
• Works well for nominal data such as colors or cities.
• Easy for models to interpret.
cons:
• Can create many columns when there are many categories.
• Increases memory usage and dataset size.
• May cause the curse of dimentionality
Label Encoding:
pros:
• Simple and easy to implement.
• Creates only one additional numerical column.
• Uses less memory than one-hot encoding.
• Useful for ordinal categories.
cons:
• Can introduce a false sense of order between categories.
• Numerical values may be incorrectly interpreted as having meaningful differences.
• Generally unsuitable for nominal categories with no natural order.

In [64]:
# num_cols = df.select_dtypes(include=['int64', 'float64']).columns
num_cols = ['age','fnlwgt','education_num','capital_gain',
                  'capital_loss','hours_per_week']
for col in num_cols:
    print(col,':', df[col].skew())

age : 0.5576631514973127
fnlwgt : 1.4477029083495352
education_num : -0.3095002599899914
capital_gain : 11.949402833551455
capital_loss : 4.592702423271812
hours_per_week : 0.22875887785250407

In [67]:
# features 1
df['total_capital'] = df['capital_gain'] - df['capital_loss']
df['total_capital']

0        0.021740
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...
32556    0.000000
32557    0.000000
32558    0.000000
32559    0.000000
32560    0.150242
Name: total_capital, Length: 32537, dtype: float64

In [77]:
# features 2
df['total_time'] = df['hours_per_week'] / df['age']
df['total_time']

0        1.345855
1        0.414109
2        1.345855
3        1.345855
4        1.345855
           ...
32556    1.276837
32557    1.345855
32558    1.345855
32559    0.655673
32560    1.345855
Name: total_time, Length: 32537, dtype: float64

In [78]:
# skewness
real_num_cols = ['age','fnlwgt','education_num','capital_gain',
                 'capital_loss','hours_per_week',
                 'total_capital','total_time']

for col in real_num_cols:
    print(col, df[col].skew())

age 0.0
fnlwgt 1.4477029083495352
education_num -0.3095002599899914
capital_gain 11.949402833551455
capital_loss 4.592702423271812
hours_per_week 0.22875887785250407
total_capital 0.7115583716427498
total_time 0.22875887785250468

In [80]:
# log function
df['capital_gain_log'] = np.log1p(df['capital_gain'])
df['capital_loss_log'] = np.log1p(df['capital_loss'])
df['total_capital_log'] = np.log1p(df['total_capital'])
df['fnlwgt_log'] = np.log1p(df['fnlwgt'])

In [82]:
# skewness

num_cols = ['age','education_num','hours_per_week','total_time',
                 'capital_gain_log','capital_loss_log','total_capital_log','fnlwgt_log']

for col in num_cols:
    print(col, df[col].skew())

age 0.0
education_num -0.3095002599899914
hours_per_week 0.22875887785250407
total_time 0.22875887785250468
capital_gain_log 10.667468268772069
capital_loss_log 4.493061511386472
total_capital_log nan
fnlwgt_log 1.0168372448632765

Skewness analysis was performed on  features , and the log functions are applied on high skewness features,but the features like capital_loss_log changes moderately.

Thus the transformation improved the data for modelling pupose.